### ISSUE TITLE
PyPI package not found

### ISSUE THREAD

**Issue by fepegar** [PySport/matplotvideo#1]
Hi,

I'm trying to install the package using `pip` but I get the following error:

```python-traceback
ERROR: Could not find a version that satisfies the requirement matplotvideo (from versions: none)
ERROR: No matching distribution found for matplotvideo
```

Tried on macOS and Ubuntu 18.04.

**Comment by fepegar** [comment]
Nevermind, I was calling using Python 3.6 and I just saw `matplotvideo` requires at least 3.7.

**Comment by koenvo** [comment]
Owh, good point because I think there is no reason why it shouldn’t work on python 3.6... I mistakenly added the restriction. Let me do some additional testing for 3.6 and update the package.

**Comment by mauriciomau0** [comment]
Hi, the same error: 

ERROR: Could not find a version that satisfies the requirement matplotvideo (from versions: none)
ERROR: No matching distribution found for matplotvideo

Tried on Windows and python 3.8.2

**Comment by koenvo** [comment]
interesting @mauriciomau0 . To make sure it's an issue with the matplotvideo package: you are able to installed other packages, right?

I might still have some wrong settings in the setup.py file. I'll dig into this and let you know.

**Comment by koenvo** [comment]
@fepegar @mauriciomau0 can you try again? I wasn't able to test it on windows yet, but i was able to install using pip on alpine-python 3.6 and 3.8

**Comment by mauriciomau0** [comment]
Yes, it works. Thank you!!
