### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'cv2'

### ISSUE THREAD

**Issue by cryoguy** [PySport/matplotvideo#3]
Getting the following error with opencv4 and python3.8.  Correct the 3 `cv2.cv2` occasions and the error is gone.

`AttributeError: module 'cv2' has no attribute 'cv2'`

**Comment by koenvo** [comment]
Thanks for your message. Would you mind creating a pull request that tries to import in both ways?

**Comment by cryoguy** [comment]
I think I did it, with fork. Thanks for the code. I was looking hard for this,

**Comment by koenvo** [comment]
Great to hear! Just curious: what is your use case?

**Comment by cryoguy** [comment]
I want to label video and data from tracking sensor.  I need to add the frame info to a dataframe and export csv.  I am not very fluent in python. so it will take some learning.
